* Глава 1
  Убеждения, что эта чудо книга позволит вам учить что угодно эффективнее, истории 
из жизни. 
Мол я не знала математику и вообще она мне не давалась. А потом трах бабах.
* Глава 2 
** Настройте свой «мыслительный насос»
Когда вы впервые начинаете просматривать главу учебника по математике или
естественным наукам, полезно пробежать глазами весь раздел, составляя себе общую
картину: взглянуть не только на схемы, диаграммы и фотографии, но и на заголовки
разделов, выводы и даже на вопросы в конце текста (если они есть). На первый взгляд
такой подход кажется нелогичным — вы ведь еще не читали главу! — однако он
помогает настроить «мыслительный насос». Попробуйте прямо сейчас проглядеть
всю главу и вопросы в конце. Вы удивитесь тому, насколько минута-другая, потраченная на такое
предварительное просматривание новой главы, помогает упорядочить мысли. Таким
способом еще до того, как начать внимательное ознакомление с текстом, вы создаете
незаметные нейронные зацепки для восприятия, которые облегчат вам усвоение
материала.
** 2 Типа мышления
*** Сфокусированное
Вот почему одна из характерных ошибок при изучении
математики и естественных наук состоит в том, что люди
прыгают в воду раньше, чем научатся плавать. Иными
словами, они начинают работать над заданием вслепую — не
прочитав учебника, не прослушав лекций, не просмотрев
онлайновых уроков, не поговорив с кем-нибудь знающим.
Перечисленное — рецепт для того, чтобы пойти ко дну. Это все
равно что в сфокусированном режиме «выстрелить» мыслью из
пинбол-автомата, не представляя себе, где может находиться
решение.
*** Расслабленное. 
Если вы пытаетесь понять или усвоить что-то новое, то
лучше выключить точное сфокусированное мышление и
включить рассеянный режим, позволяющий видеть широкую
картину.
** Избавление от прокрастинации
Кратковременная, но интенсивная концентрация
Если прокрастинация — ваша слабость (как у многих из нас) и вы часто откладываете
дела на потом, то вот вам подсказка. Выключите телефон и заглушите любые звуки
или сигналы (компьютерные тоже), которые могут прервать процесс. Затем
поставьте таймер на 25 минут, сделайте 25-минутный перерыв в работе и
сосредоточьтесь на задаче — любой. Не думайте о том, как ее закончить, просто
сфокусируйтесь на поисках решения. По истечении 25 минут вознаградите себя:
побродите по Интернету, проверьте сообщения в телефоне, сделайте что-нибудь
приятное. Награда так же важна, как и работа над задачей. Вы сами удивитесь,
насколько продуктивным может быть 25-минутный отрезок времени, особенно когда
вы концентрируете внимание на самой работе, а не на ее завершении.
** Остановитесь и вспомните
   Закройте книгу и отведите взгляд. Каковы основные идеи этой главы? Если вам
не удалось вспомнить с первой попытки — ничего страшного. Продолжайте
практиковать этот метод, и со временем вы заметите, что и читать, и
запоминать становится легче.
* Глава 3
  
