* Выжить на сотку в день
По плану нужно выжить до 29 декабря 2020г. включительно. Мои финансы составляют 1700 рублей. 
** День 1
Жратвы еще навалом. Никаких проблем возникнуть не должно. Однако, еда которая имеется однотипная.
Упрек в сторону составления рациона. Вечером посещу магазин и потрачу свою сотку. 
Проблем быть не должно, может подосрать поездка на работу. На метро уйдет 60-70р. И придется топать пешком. Там мороз. 
А пока надо поработать. Я решил отложить пока эту сотку. Пока еды в достатке. 
В итоге к концу дня у меня не потраченная сотка. Завтра в магазине разгуляюсь. 

 Завтрак: 
Кусочек пиццы, черный чай с сахаром.

 Обед:
Картошка жаренная на сале и кусочек адыгейского сыры, стакан молока и стакан томатного сока с минералкой.

 Ужин:  
Креветки, салат из яблока, банана, клубники, с молоком.

Поиграл в VR на 300ккал, спорт 6 неделя. 16 жим, пресс и приседания. Завтра будет уже по 17.

Покупок за сегодня не было. Самочувствие ок. 

Каждый день прохожу англ в дуалингво. Записывать не буду, за моим прогрессом следит приложение. 
Но вот хотел бы еще прочитать гарри поттер и методы рац. мышления в ориге на англ.

Немного почитал, Станиславского, 2й том. Актерское мастерство.
Наверно стоит записать. по главам, что отложилось в памяти.
Нет, это отнимает нереально много времени, лучше надиктовать на диктофон.
** День 2

	Жратвы оказалось не так уж и навалом. 

Завтрак: Чай и жареная картоха.
Обед: Какие то детские печенья и грецкие орехи, по принципу что нашел то и сожрал.
Ужин: Запилил хачапури лодочку, чай.



Поиграл в VR на 60ккал, спорт 7 неделя. 17 жим, пресс и приседания. 

Покупок за сегодня не было. Самочувствие ок. Ресурсов все еще 1700р.

** День 3

	Еда почти все. Осталось на 1 день.

Завтрак: Драники, чай лимончик.
Ужин: Курочка запеченная, чай, печенье в клеточку.

Поиграл в VR на 60ккал, спорт 7 неделя. 17 жим, пресс и приседания. 
Нихрена полезного не сделал. Сходил к зубному разве что, на 7300!!!

Покупки ниже. Самочувствие ок. Ресурсов осталось 1384.83

** День 4
   Хочется чего нибудь вкусного!!!

Завтрак: Бутер масло сыр, чай.
Обед: Борщ. 
Ужин: Отварная, обжаренная капуста, жареная куриная грудка, чай, печенье в клеточку, 2 яйца, хлеб. 


Спорт 7 неделя. 17 жим, пресс и приседания. Думаю, это слишком мало, перескочим сразу к 20 с завтрашнего дня. 

** День 5
   Пошла жара. Пришлось ехать на работу. Кое кто другой должен был оплатить эти платы, но не вышло.

Обед: Бургер кинг, на 199р СЭТ’Ъ.
Ужин: Пивасик !!!!!! и прочая закуска.

Итого минус дохуя)
Короче, у меня осталось что-то где то примерно. мало. 434.93. До 30 числа.
Спортом не занимался, ничего полезного не сделал. ВСЕ ОЧЕНЬ ПЛОХО) Вот что работа с людьми делает.

** День 6
Завтрак: Бутер с сыром и чай.
Ужин: Хендмейд вок, и халявная филка с колой.

Спорт 7 неделя. 20 жим, пресс и приседания. Все еще мало думаю увеличить до 25. Завтра.	
Потихоньку начал разбираться с емаком и орг модом, дабы дневник стал нормальным инструментом, помогающим контролировать жизнь. 

** День 7
	Пришла мысля затарится спортпитом.

Завтрак: Картоха жареная с салом и гренками, чай.

Спорт 25 жим, пресс и приседания. Поднимем ставки. По 30 в день, с завтрашнего.

* Феил я заболел
Продержался 7 дней. Заболел, все пошло коту под хвост. Позже возможно попробую еще раз.
