* Include <> "" 
"" - сначала искать инклюды локально, <> - глобально.
#include "some.h", то сначала будут просмотрены локальные (по отношению к проекту) папки включения файлов. Если использовать #include <some.h>,
то сначала будут просматриваться глобальные (по отношению к проекту) папки включения файлов.
Глобальные папки включения - это папки, прописанные в настройке среды разработки, локальные - это те, которые прописаны в настройках проекта.
* Pragma pack
#pragma pack(push,1)
#pragma pack(pop)
* Параметр или аргумент
Параметром (формальным параметром) функции называется переменная в функции, которая будет содержать передаваемое снаружи входное значение.
Аргументом называют фактическую переменную или выражение, значение которого используется как входное значение при вызове функции.

#+name: the-content
#+begin_src с++
double Negate(double x)
{
    return -x;
}
#+end_src

Здесь x — параметр функции Negate.

#+name: the-content
#+begin_src с++
double r = Negate(5.0);
#+end_src

Здесь 5.0 — аргумент вызова функции Negate.

Таким образом, набор параметров (то есть, «переданных снаружи» переменных) функции фиксирован,
а вот аргументы (то есть, выражения, значения которых попадут в эти переменные) при каждом из вызовов могут быть свои.
